pipeline {

    agent any

    environment {
        SONAR_SCANNER = tool 'SonarScanner'
        AWS_DEFAULT_REGION = 'us-east-1'

        S3_BUCKET = ecommerce-frontend-buckets 
        CLOUDFRONT_DISTRIBUTION_ID = E3BOCWTOPS1NNG
    }

    stages {

        stage('Install Dependencies') {
            steps {
                dir('frontend') {
                    sh '''
                        npm ci
                    '''
                }
            }
        }

        stage('Build React App') {
            steps {
                dir('frontend') {
                    sh '''
                        npm run build
                    '''
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('frontend') {
                    withSonarQubeEnv('sonarqube') {
                        sh """
                            ${SONAR_SCANNER}/bin/sonar-scanner \
                            -Dsonar.projectKey=ecommerce-frontend \
                            -Dsonar.projectName=ecommerce-frontend \
                            -Dsonar.sources=src
                        """
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 10, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Update Environment Config') {
            steps {
                dir('frontend') {
                    sh '''
                        echo "Updating frontend environment configuration..."

                        if [ -f public/env-config.js ]; then
                            echo "env-config.js found"
                            cat public/env-config.js
                        else
                            echo "No env-config.js found. Continuing..."
                        fi
                    '''
                }
            }
        }

        stage('Final Build') {
            steps {
                dir('frontend') {
                    sh '''
                        rm -rf build
                        npm run build
                    '''
                }
            }
        }

        stage('Upload Build Files to S3') {
            steps {
                dir('frontend') {
                    sh '''
                        aws s3 sync build/ s3://${S3_BUCKET}/ --delete
                    '''
                }
            }
        }

        stage('CloudFront Invalidation') {
            steps {
                sh '''
                    aws cloudfront create-invalidation \
                    --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} \
                    --paths "/*"
                '''
            }
        }
    }

    post {
        success {
            echo '======================================'
            echo 'FRONTEND CI/CD PIPELINE SUCCESSFUL'
            echo '======================================'
        }

        failure {
            echo '======================================'
            echo 'FRONTEND CI/CD PIPELINE FAILED'
            echo '======================================'
        }

        always {
            echo 'Frontend pipeline completed.'
        }
    }
}
